### ISSUE TITLE
cp4d-app fails to sync because cp4d namespace not found

### ISSUE THREAD

**Issue by David-M-IBM** [IBM/cloudpak-gitops#193]
When following the install instructions for cp4d Argo will give an error that the namespace cp4d isn't found

<img width="1735" alt="image (34)" src="https://user-images.githubusercontent.com/83517881/206518436-fe1b6759-5e0f-49dd-b775-ad6b69e14ff2.png">

I was able to reproduce it twice by following the install instructions doc up to the creation of the cp4d-app

I also ran into a bug where it errors in Argo saying that "cp4d-cluster-roles" already exists, but that was able to be resolved by just syncing again. In order to get past this error I just manually created the cpd4d namespace.

<img width="1755" alt="image (35)" src="https://user-images.githubusercontent.com/83517881/206518319-80861e69-6020-49c5-a399-0e33be3a20a8.png">

**Comment by nastacio** [comment]
Tim Robinson tried the instructions and successfully installed CP4D following the instructions.
