### ISSUE TITLE
rhacm.md doc for argocd-control-plane create missing --helmset for repoURL

### ISSUE THREAD

**Issue by slipsibm** [IBM/cloudpak-gitops#332]
I was having trouble when trying to use my own repo to test out of. When I tried installing the rhacm-control-plane, The ArgoCD app would file with an error message about not having permissions or something. I went back and noticed that 

`      --helm-set repoURL=${gitops_url:?} \`
was missing from the creation of the argocd-control-plane create statement. once I added this line in, and recreated the ArgoCD Control Plane, everything worked ok.

**Comment by nastacio** [comment]
Thanks for validating and fixing this. A welcome contribution.
