### ISSUE TITLE
Install Documentation

### ISSUE THREAD

**Issue by bmos299** [IBM/cloudpak-gitops#62]
**Describe the bug**
Using the install documentation at https://github.com/IBM/cloudpak-gitops/blob/main/docs/install.md.

**To Reproduce**
Pam and I are walking through the install docs.

3.  Argo-app.  
-- why am I putting this on?
-- how long will it take and should we wait ?  (watch the sync?)
4.  cp-shared.  Explain what it is doing.
7.  cicd-app tile is still yellow.
8. can this be deleted as step 11 also says create?
10.  Parameters are set with defaults so people don't have to necessarily modify do they? 
12.  waiting and putting operators on.  It looks like operators are in ibm-cloudpaks, which is fine, but not typical so we may want to tell them. 
....we are still working on this but wanted to give you a heads up.

**Comment by nastacio** [comment]
Agree with most. Exceptions:

> 6. can this be deleted as step 11 also says create?

There are two applications

>  8. It looks like operators are in ibm-cloudpaks, which is fine, but not typical 

It is modeled after `ibm-common-services`. All Cloud Paks install on that same namespace. If someone wants a different namespace, they can set the corresponding parameter in the ArgoCD `Application` resource.

**Comment by nastacio** [comment]
`5. cicd-app tile is still yellow.` has since been addressed with #75 , where this unecessary app is no longer deployed

**Comment by nastacio** [comment]
All the non-question issues have been addressed in the documentation.

Also, the documentation has evolved a lot in the meantime, so issues and questions may have changed significantly.

Closing it.
